apiVersion: v1
kind: Service
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  selector:
    app: jaeger
  ports:
    - name: http-query
      port: 16686
      targetPort: 16686
    - name: http-collector
      port: 14268
      targetPort: 14268
    - name: grpc-query
      port: 16685
      targetPort: 16685
    - name: grpc-collector
      port: 14267
      targetPort: 14267
