apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth
  name: auth
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - image: tvksp8/auth:latest
          imagePullPolicy: Never
          name: auth
          resources:
            requests:
              cpu: "0.5"
              memory: "500M"
            limits:
              cpu: "0.5"
              memory: "500M"
      dnsPolicy: ClusterFirst
      restartPolicy: Always