# graylog-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: graylog
spec:
  selector:
    app: graylog
  ports:
    - name: http
      port: 9000 # Порт для доступа к Graylog Web Interface
      targetPort: 9000
    - name: tcp-logs
      port: 12201 # TCP-порт для отправки логов
      targetPort: 12201
  type: LoadBalancer