apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['prometheus.default:9090'] # Адрес и порт Prometheus
      
      - job_name: 'postgres-exporter'
        static_configs:
          - targets: ['postgres-exporter.default:9187'] # Имя сервиса или IP-адрес экспортера PostgreSQL
      
      - job_name: 'redis-exporter'
        static_configs:
          - targets: ['redis-exporter.default:9121'] # Имя сервиса или IP-адрес экспортера Redis