apiVersion: v1
kind: Service
metadata:
  labels:
    app: email
  name: email
  namespace: default
spec:
  ports:
    - port: 1112
      protocol: TCP
      targetPort: 1112
  selector:
    app: email
  sessionAffinity: None
  type: ClusterIP