apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
    - protocol: TCP
      port: 9999  # Порт, на который мы хотим маршрутизировать трафик
      targetPort: 9200  # Порт контейнера Elasticsearch
  type: ClusterIP  # Внутренний сервис для доступа изнутри кластера