apiVersion: v1
kind: Service
metadata:
  labels:
    app: request
  name: request
  namespace: default
spec:
  ports:
    - port: 1111
      protocol: TCP
      targetPort: 1111
  selector:
    app: request
  sessionAffinity: None
  type: ClusterIP